name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    name: Lint and Test with Node.js ${{ matrix.node }}
    strategy:
      matrix:
        node:
          - 16
          - 18
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: latest

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Build, Lint and Test
        run: pnpm run-s build lint test
        env:
          EFF_NO_LINK_RULES: true
          PARSER_NO_WATCH: true

      - name: Codecov
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5
